# -*- coding: utf-8 -*-
"""population_dict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YXG-5dsF8tjppMcK5SklZ47Srnsd2Dem
"""

population_dict = {'Russia':144_000_000, 
                   'Us':350_000_000,
                   'Belarus': 9_500_000,
                   'Brazil':209_500_000,
                   'China':1_393_000_000,
                   'Egypt': 98_420_000,
                   'Finland':5_518_000,
                   'Germany':83_020_000,
                   'Iceland':365_000,
                   'India':1_353_000,
                   'Latvia':1_920_000,
                   'Spain':46_940_000,
                   'Sweden':10_230_000,
                   'Turkey':82_000_000,
                   'Uk':66_650_000}